---
title: "odd_retail_sales_2017_02"
author: "Can Koyuturk"
date: "October 27, 2018"
output: html_document
---

ODD Assignment BDA 503

```{r}
tmp<-tempfile(fileext=".xls")
download.file("https://github.com/MEF-BDA503/pj18-koyuturkc/blob/master/odd_retail_sales_2017_02.xls?raw=true",destfile=tmp)
raw_data<-readxl::read_excel(tmp,skip=7,col_names=FALSE)
file.remove(tmp)
```

```{r}
raw_data <- raw_data %>% slice(-c(43,44))
head(raw_data)
```
```{r}
colnames(raw_data) <- c("brand_name","auto_dom","auto_imp","auto_total","comm_dom","comm_imp","comm_total","total_dom","total_imp","total_total")
odd_retail_sales_2017_02 <- raw_data %>% mutate_if(is.numeric,funs(ifelse(is.na(.),0,.))) %>% mutate(year=2017,month=2)
print(odd_retail_sales_2017_02,width=Inf)
```

```{r}
saveRDS(odd_retail_sales_2017_02,file="~/YOUR_OWN_PATH/odd_retail_sales_2017_02.rds")
```

```{r}
odd_retail_sales_2017_02 %>% 
  filter(auto_total > 0 & comm_total > 0) %>%
  select(brand_name,total_total) %>%
  arrange(desc(total_total))
```




